### ISSUE TITLE
Need better messages when CUDA environment is not set or is set partially

### ISSUE THREAD

**Issue by pearu** [conda-forge/nvcc-feedstock#30]
When CUDA environment is not set and trying to conda build nvcc-dependent recipe, the build fails with output:
```
...
+GXX=$PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
****************************************************************************************************
None
****************************************************************************************************
Traceback (most recent call last):
  File "/home/pearu/mconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/utils.py", line 406, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/pearu/mconda3/lib/python3.7/site-packages/conda_build/utils.py", line 386, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/pearu/mconda3/conda-bld/omniscidb-cuda_1572622740779/work/conda_build.sh']' returned non-zero exit status 1.
``` 
The failure is caused by the fact that `$CUDA_HOME/bin` has not been added  to PATH but it is impossible to figure out that from the above error message.

**Comment by jakirkham** [comment]
Interesting. Would figure we would see [this error message]( https://github.com/conda-forge/nvcc-feedstock/blob/ad6177324648b943f0949b7b286dffe1aa3230b2/recipe/install_nvcc.sh#L39 ), but it sounds like that is not happening.

**Comment by pearu** [comment]
It could be because `CUDA_HOME` was defined but the `PATH` didn't include `$CUDA_HOME/bin`.

**Comment by pearu** [comment]
When `gdb-cuda` is not in PATH, the `which gdb-cuda` will exit the activation script immediately, hence, no messages.
PR #32 fixes this issue.
